-- AlterTable
ALTER TABLE "users" ADD COLUMN     "balance" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "total_expenses" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "total_incomes" DECIMAL(10,2) NOT NULL DEFAULT 0.00;
